### ISSUE TITLE
El refresco/actualizacion tarda mucho cuando mueves el mapa

### ISSUE THREAD

**Issue by javierbds** [s-nt-s/TAI-Madrid#10]
Si hubiera alguna forma de deshabilitar los mapas por satelite (terreno) supongo que iria mas rapido. Es suposición, no he programado con google maps ...

**Comment by s-nt-s** [comment]
Dices en https://www.google.com/maps/d/u/0/viewer?mid=1pv8aiDcgFZWtE7_0H8LVUupTo5z8_fM8 ?

Yo solo pongo las chinchetas, el mapa ha de funcionar igual que cuando entrar en google maps para cualquier otra cosa. Las vista las activa el usuario, yo lo veo normal.

**Comment by javierbds** [comment]
Ahora tambien me va bien a mi ... Caches?
