### ISSUE TITLE
Posibles puestos omitidos Cuenca

### ISSUE THREAD

**Issue by dfjhh** [s-nt-s/TAI-Madrid#11]
En RPT http://transparencia.gob.es/transparencia/transparencia_Home/index/PublicidadActiva/OrganizacionYEmpleo/Relaciones-Puestos-Trabajo/RPT-MTMS.html, se puede ver que los puestos de la "UNIDAD PROVINCIAL DE INFORMATICA DE CUENCA", como "ANALISTA" con ids 5118316, 5118430, 5118431, 5118432 y 5118447, correponden a TAIS (C1, nivel 18).

Estos no constan en el mapa interactivo.

**Comment by s-nt-s** [comment]
Estos puestos se estan teniendo en cuenta, se ve en: https://s-nt-s.github.io/TAI-Madrid/724/16/index.html el problema es que todos pertenencen a `48072 - UNIDAD PROVINCIAL DE INFORMATICA DE CUENCA`, de la cual no tenemos dircción, así que se asignan al organismo padre, es cual es `49260 - S. DE E. DE LA SEGURIDAD SOCIAL` y este, como ya tiene muchos puestos, cuando muestra la descripción en `Google Maps` aparece cortada y no se ven los últimos puestos, entre los que estan los que tu apuntas.

Por lo tanto la solución es conseguir la dirección de `48072 - UNIDAD PROVINCIAL DE INFORMATICA DE CUENCA` ¿sabes cual es?

**Comment by dfjhh** [comment]
La que tenéis asignadas al puesto 3319088/20 - COORDINADOR / COORDINADORA INFORMATICO N20, pienso que es la correcta, Eras del Tio Cañamon 2 4, 16004, Cuenca, Castilla La Mancha, España.

**Comment by s-nt-s** [comment]
Mirando https://contrataciondelestado.es/wps/wcm/connect/7cb14bc3-c388-4d81-bfa8-0a3166839583/DOC201803021231347103-18_PPT-Anexo%2BI%2B-%2BSedes.xlsx&attachment=true parece que `48072 - UNIDAD PROVINCIAL DE INFORMATICA DE CUENCA` esta en `Parque San Julián, 7, 16001 Cuenca` ¿puedes confirmarmelo?

**Comment by dfjhh** [comment]
En el 7 del Parque de San Julián está tesorería de la seguridad social. Puede que como dices este hay y no en la otra oficina de la SS en Eras del Tio Cañamon. Iré a preguntar insitu mañana para confirmarlo.

Por aclararlo,  en el 12 de la misma calle está Hacienda/AEAT y sé que hay área de informática pues he ido más de una vez por no funcionar la página/formularios de la agencia tributaria. (El INEM está al lado también).

Por otro lado en la SS he visto el puesto 5118115, un A2C1 con un nivel 22, que supongo habréis descartado por el nivel.

**Comment by pikachuEMR** [comment]
He hecho un pull request para actualizar las direcciones de las Unidades Provinciales de Informática (UPIs) de la Gerencia de Informática de la Seguridad Social (GISS): https://github.com/s-nt-s/TAI-Madrid/pull/13

@dfjhh coméntanos si efectivamente la UPI está en esa dirección (Parque San Julián, 7, 16001 Cuenca) para que podamos confirmar la teoría de que las UPIs suelen estar en la TGSS.

**Comment by dfjhh** [comment]
Hoy he ido (con un dia de retraso sobre lo previsto) a dicho lugar y efectivamente la UPI de GISS está en esa dirección.

**Comment by s-nt-s** [comment]
ok, resuelto.
