### ISSUE TITLE
¿Organismo duplicado?

### ISSUE THREAD

**Issue by dfjhh** [s-nt-s/TAI-Madrid#12]
Buenos dias, 
Parece ser que las aŕeas, E04232901 y [EA0012944](https://administracion.gob.es/pagFront/espanaAdmon/directorioOrganigramas/fichaUnidadOrganica.htm?idUnidOrganica=95896) son la misma, correspondiendo los datos de localización a esta última.

**Comment by s-nt-s** [comment]
Gracias. En la proxima versión apareceran fusionados.
