### ISSUE TITLE
puestos vacantes que no nos van a ofertar

### ISSUE THREAD

**Issue by pikachuEMR** [s-nt-s/TAI-Madrid#18]
Es muy probable que algunos puestos vacantes de los que figuran en la lista (https://s-nt-s.github.io/TAI-Madrid/destinos.html) no puedan aparecer en nuestra oferta de destinos. Algunos puestos se han cubierto en estos últimos meses (con posterioridad a las RPTs), mientras que otros se han ofertado en concursos generales abiertos en julio.

Propongo anotarlo de alguna forma en la lista y en el mapa, quizás con algún subíndice o cambio de color. Los vacantes los marco con V en la primera columna de las siguientes listas:

1.- Puesto que ha sido cubierto con posterioridad a la fecha de la RPT:
V	4845404	MADRID		ANALISTA PROGRAMADOR				18	A2C1

2.- Puesto que se encuentra en concurso abierto del Ministerio de Justicia:
V 	3203146	MADRID		ANALISTA PROGRAMADOR				18	A2C1

3.- Puestos que se encuentran en concurso abierto del Ministerio de la Presidencia, Relaciones con las Cortes e Igualdad:
	4694416	MADRID		PROGRAMADOR / PROGRAMADORA DE SEGUNDA		15	C1
V	2323903 MADRID		PROGRAMADOR / PROGRAMADORA DE PRIMERA		17	C1C2
	1964980	MADRID		ANALISTA PROGRAMADOR				18	C1C2
	4003797	MADRID		ANALISTA PROGRAMADOR				18	C1C2
V	817247	MADRID		ANALISTA PROGRAMADOR				18	C1C2
	2144396 MADRID		OPERADOR / OPERADORA DE CONSOLA			15	C1

4.- Concurso abierto del Ministerio de Política Territorial y Función Pública:
	2269397	ALICANTE	TECNICO / TECNICA DE REDES INFORMATICAS		18	A2C1
V	4201990	ALICANTE	PROGRAMADOR / PROGRAMADORA DE SEGUNDA		15	C1
V	1294043	BALEARES	TECNICO / TECNICA DE REDES INFORMATICAS		18	A2C1
V	4782124	BALEARES	TECNICO / TECNICA DE REDES INFORMATICAS		18	A2C1
V	1533496	BARCELONA	TECNICO / TECNICA DE REDES INFORMATICAS		18	A2C1
V	3182236	CADIZ		TECNICO / TECNICA DE REDES INFORMATICAS		18	A2C1
	4786693	CADIZ		TECNICO / TECNICA DE REDES INFORMATICAS		18	A2C1
V	4207567 GUIPUZCOA	TECNICO / TECNICA DE REDES INFORMATICAS		18	A2C1
V	846484	MURCIA		TECNICO / TECNICA DE REDES INFORMATICAS		18	A2C1
V	2500123	NAVARRA		TECNICO / TECNICA DE REDES INFORMATICAS		18	A2C1
V	847427	RIOJA		PROGRAMADOR / PROGRAMADORA DE PRIMERA		17	C1
V	4305396	SEVILLA		TECNICO / TECNICA AUXILIAR DE INFORMATICA	16	C1
	4786694	TENERIFE	TECNICO / TECNICA DE REDES INFORMATICAS		18	A2C1
V	4786695	TENERIFE	TECNICO / TECNICA DE REDES INFORMATICAS		18	A2C1

Referencias:
[1] https://www.boe.es/diario_boe/txt.php?id=BOE-A-2018-10329
[2] https://www.boe.es/boe/dias/2018/07/21/pdfs/BOE-A-2018-10302.pdf
[3] https://www.boe.es/boe/dias/2018/07/12/pdfs/BOE-A-2018-9733.pdf
[4] https://www.boe.es/boe/dias/2018/07/09/pdfs/BOE-A-2018-9564.pdf

**Comment by s-nt-s** [comment]
Ya lo hemos hablado en el grupo, pero para que quede reflejado aqui lo resumo:

Estaría bien poder automatizar la busqueda de nombrammientos para sacar las plazas que ya no estan vacantes desde la última publicación de los `RPT`, pero si usamoshttps://www.boe.es/buscar/personal.php?campo%5B0%5D=TIT&dato%5B0%5D=&operador%5B0%5D=and&campo%5B1%5D=ID_RNG&dato%5B1%5D=&operador%5B1%5D=and&campo%5B2%5D=ID_DEM&dato%5B2%5D=&operador%5B2%5D=and&campo%5B3%5D=DOC&dato%5B3%5D=Nombramientos%2C+situaciones+e+incidencias&operador%5B3%5D=and&campo%5B4%5D=NBO&dato%5B4%5D=&operador%5B4%5D=and&campo%5B5%5D=DOC&dato%5B5%5D=&operador%5B6%5D=and&campo%5B6%5D=FPU&dato%5B6%5D%5B0%5D=31%2F03%2F2018&dato%5B6%5D%5B1%5D=24%2F07%2F2018&operador%5B7%5D=and&campo%5B7%5D=FAP&dato%5B7%5D%5B0%5D=&dato%5B7%5D%5B1%5D=&page_hits=2000&sort_field%5B0%5D=FPU&sort_order%5B0%5D=desc&sort_field%5B1%5D=ref&sort_order%5B1%5D=asc&accion=Buscar vemos que no aparece https://www.boe.es/diario_boe/txt.php?id=BOE-A-2018-10329 así que debe haber algún problema con el buscador.

Seguire investigando...

**Comment by pikachuEMR** [comment]
Como decía @galaica, tiene que ser algún error de indexación. Aunque efectivamente el texto "Nombramientos, situaciones e incidencias" no aparece dentro del epígrafe TEXTO del BOE que no aparece en esa búsqueda (https://www.boe.es/diario_boe/txt.php?id=BOE-A-2018-10329), sí aparecen en la búsqueda otros BOEs en los que tampoco aparece ese texto dentro del epígrafe TEXTO.

¿Y si esquivamos el problema dejando en blanco el campo Texto y buscando en su lugar Título="resuelve"?

https://www.boe.es/buscar/personal.php?campo%5B0%5D=TIT&dato%5B0%5D=resuelve&operador%5B0%5D=and&campo%5B1%5D=ID_RNG&dato%5B1%5D=&operador%5B1%5D=and&campo%5B2%5D=ID_DEM&dato%5B2%5D=&operador%5B2%5D=and&campo%5B3%5D=DOC&dato%5B3%5D=&operador%5B3%5D=and&campo%5B4%5D=NBO&dato%5B4%5D=&operador%5B4%5D=and&campo%5B5%5D=DOC&dato%5B5%5D=&operador%5B6%5D=and&campo%5B6%5D=FPU&dato%5B6%5D%5B0%5D=31%2F03%2F2018&dato%5B6%5D%5B1%5D=11%2F09%2F2018&operador%5B7%5D=and&campo%5B7%5D=FAP&dato%5B7%5D%5B0%5D=&dato%5B7%5D%5B1%5D=&page_hits=2000&sort_field%5B0%5D=FPU&sort_order%5B0%5D=desc&sort_field%5B1%5D=ref&sort_order%5B1%5D=asc&accion=Buscar

**Comment by s-nt-s** [comment]
He creado `fuentes/get-nombramientos.py` para obtener automaticamente todos los BOEs con nombramientos.

Luego `crear_datos.py` usa esa información para machacar el estado de los puestos vacantes con el nombre del BOE en el que aparece el nombramiento. Se genera el fichero `debug/falsas_vacantes.txt` para ver cuales son esos puestos.

Finalmente esto se representa en el listado de destinos con una `B` (de BOE) con un link al BOE en el que sale el puesto, en vez de la `V` de vacante que habia antes.

Adicionalmente, en el mapa estos puestos dejaran de generar pestañas verdes.

En total se pierden 36 vacantes.

**Comment by pikachuEMR** [comment]
Vale, he visto que has optado por dejar vacío el filtro en el buscador y después buscar "Nombramientos, situaciones e incidencias". Después buscas el código de puesto en todo el texto del BOE... o en la conversión a texto del PDF del BOE, si detectas que hay imágenes pegadas. Mola.

Hay una pequeña pega: que el código de puesto aparezca en el texto del BOE no implica que haya sido cubierto. En algunos casos, como por ejemplo el puesto 4667561 en Sevilla (https://www.boe.es/boe/dias/2018/04/10/pdfs/BOE-A-2018-4848.pdf) lo que dice el BOE es precisamente que quedó desierto. Entiendo que las veces que ocurra esto serán las menos, y además tiene que ser difícil programarlo para que detecte también si queda o no desierto. Yo lo dejaría como está, o quizás pondría "V?".


Sobre los concursos abiertos que se encuentren, pueden pasar dos cosas:
A.- El concurso está abierto. Mientras esté abierto, sabemos con seguridad que no se nos puede ofertar.
B.- El concurso ha sido resuelto con posterioridad. En este caso, tal como lo tienes programado, detectará el nombramiento (se "pisaría" la detección), con lo que no es problema. La única eventualidad que se escapa en este caso B es que el puesto haya quedado desierto en el concurso.

**Comment by s-nt-s** [comment]
> Entiendo que las veces que ocurra esto serán las menos, y además tiene que ser difícil programarlo para que detecte también si queda o no desierto

Efectivamente, no creo que merezca la pena hacer la distinción.

Por otra parte he cambiado el código (y he editado mi anterior mensaje) para incluir los concursos, ya que he llegado a la misma conclusión que tu (que da más o menos igual si el concurso esta abierto o cerrado)

Teniendo en cuenta que lo de que un puesto este vacante solo lo usamos a titulo informativo (no influye ni en los filtros ni en nada), y ya sabiamos de partida que es algo muuuuy orientativo, creo que no importa mucho si se pierde alguno. Más despues de leer esto:

> La columna de estado pretende simplificar la información ofrecida al ciudadano, por lo que no se corresponde estrictamente con situaciones jurídicas. La calificación de un puesto como vacante tampoco es objeto de actualización y no excluye que a la fecha de extracción de datos dicho puesto esté comprometido o se prevea su compromiso en algún procedimiento de provisión o en una modificación de la relación de puestos de trabajo.

en http://transparencia.gob.es/transparencia/transparencia_Home/index/PublicidadActiva/OrganizacionYEmpleo/Relaciones-Puestos-Trabajo.html

Ahora lo interesante sería saber si con una aproximación parecida podriamos directamente descartar algún puesto como TAI sabiendo que ha salido en tal o cual concurso. Es decir, como para suponer que un puesto es TAI basicamente filtramos por "a que suena su titulo" seguro que se nos estan colando puestos que realmente no son TAIs pero que sin más información no se puede estar seguro. Quiza saber que el puesto ha salido en X concurso de esa información extra que permita saber que algo que parece TAI realmente no es TAI.

**Comment by pikachuEMR** [comment]
> Ahora lo interesante sería saber si con una aproximación parecida podriamos directamente descartar algún puesto como TAI sabiendo que ha salido en tal o cual concurso. Es decir, como para suponer que un puesto es TAI basicamente filtramos por "a que suena su titulo" seguro que se nos estan colando puestos que realmente no son TAIs pero que sin más información no se puede estar seguro. Quiza saber que el puesto ha salido en X concurso de esa información extra que permita saber que algo que parece TAI realmente no es TAI.

Si en algún concurso aparece un funcionario del cuerpo A1188 como adjudicatario del puesto X, sabemos que el puesto X puede ofertarse a TAIs. Pero el hecho de que en algún concurso el puesto X sea adjudicado a funcionarios de otros cuerpos no es suficiente para descartarlo como ofertable a TAIs.

No sé si si me entero de la eliminación que pretendes...

**Comment by s-nt-s** [comment]
> No sé si si me entero de la eliminación que pretendes...

Si lo has entendido bien, pero por lo que dices parece que no se va a poder.
