### ISSUE TITLE
dirección del organismo E03699104 errónea en mapa

### ISSUE THREAD

**Issue by pikachuEMR** [s-nt-s/TAI-Madrid#19]
La Direccion Provincial del SEPE de Segovia aparece en Córdoba en mitad de la nada.

Iba a hacer un pull request para corregir coordenadas, pero la dirección postal sí figura en Dir3 y es correcta. Además, en el mapa tai.kml que tengo en mi fork de hace dos días sí aparecía correctamente ubicada.

¿Quizás se trate de un glitch al ejecutar coordenadas.py en el último commit?

**Comment by s-nt-s** [comment]
Encontre esta página http://www.sepe.es/direccionesytelefonosWeb/jsp/JSP_index.jsp y juzgue que sería conveniente en el caso del sepe machacar los datos dir3 con los de la página, pero se ve que no estan bien -_-U.
¿Has visto algún otro error más en el SEPE?

**Comment by pikachuEMR** [comment]
Me llamó la atención ver una chincheta nueva en Córdoba y además fuera de la capital.

No veo más errores en http://www.sepe.es/direccionesytelefonosWeb/jsp/JSP_index.jsp (o son pocos metros de distancia).

**Comment by s-nt-s** [comment]
Entonces lo arreglo via `cod_dir_latlon.txt` y listo
