### ISSUE TITLE
Documentación de las dependencias

### ISSUE THREAD

**Issue by dfjhh** [s-nt-s/TAI-Madrid#2]
Hola,
¿Sería posible documentar las dependencias/paquetes de python necesarios para su ejecución?

**Comment by s-nt-s** [comment]
hecho, ver `requirements.txt`

Además, para ejecutar `leer.py` se necesita estar en linux y disponible la erramienta pdftotext, ya que funciona mejor que la librería PyPDF2.

Pero creo que voy a generar unos json con todo y así no haga falta ejecutar `leer.py`

**Comment by s-nt-s** [comment]
Los json ya tienen todos los datos, así que si se quiere tunear la salida basta con tocar `escribir.py`, ya no hacen falta las dependencias de `leer.py` hasta que vuelvan a actualizar los datos del portal de transparencia.
