### ISSUE TITLE
Eliminar puntos `?` del mapa

### ISSUE THREAD

**Issue by s-nt-s** [s-nt-s/TAI-Madrid#23]
Si observais https://s-nt-s.github.io/TAI-Madrid/direcciones.html vereis que en algunos organismos pone `No tiene dirección, pero debería estar en XXXXX`. Esto lo pone en aquellos organismos que no tienen dirección pero se sabe en que provincia estan y tambien se sabe que no es la misma provincia en la que esta su organismo padre.

La gracia de estos organismos es que generan [los puntos den el mapa representados con `?`](https://www.google.com/maps/d/viewer?mid=1pv8aiDcgFZWtE7_0H8LVUupTo5z8_fM8) y que seria muy interesante ir descartando (ahora mismo **solo quedan ~~24~~ 1**).

Para eliminar esos `puntos ?` lo que hay que hacer es `pull requests` a `cod_dir_latlon.txt` con lineas con este formato:

```
<codigo>      <latlon>      <dirección postal>
```

Ver el propio fichero `cod_dir_latlon.txt` para más detalles.

O si te es más sencillo, rellenandolo en el excel https://docs.google.com/spreadsheets/d/18GC2-xHj-n2CAz84DkWVy-9c8VpMKhibQanfAjeI4Wc (pestaña direcciones)

La tarea es buscar esos organismos en google, en paginas de la administración publica, etc y dar con su dirección. Si no sabeis otra manera mejor, podeis sacar las coordenadas de una dirección con http://www.mapcoordinates.net/es

**Comment by dfjhh** [comment]
AALOG61 (48836) tiene tres direcciones ya que está desplegada en tres provincias ver: http://www.ejercito.mde.es/unidades/Valladolid/aalog61/Localizacion/index.html siendo la principal Base Militar "El Empecinado" Carretera de Cabezon s/n 47155 Santovenia de Pisuerga
Instituto Hidrográfico de la Armada (28959) http://www.armada.mde.es/ArmadaPortal/page/Portal/ArmadaEspannola/cienciaihm1/prefLang-es/01Presentacion--04estamosEn tiene por dirección Plaza de San Severiano 3, 11007 Cadiz
28197  Academia de Ingenieros del ejercito de tierra: http://forofuerzasarmadas.foroactivo.com/t155-academia-de-ingenieros-acing-hoyo-de-manzanares Carretera de Torrelodones a Colmenar Viejo, km 10,7 Hoyo de Manzanares, Madrid
28276  Agrupación de apoyo logistica nº 11 http://www.ejercito.mde.es/unidades/Madrid/aalog11/Localizacion Base Logística de San Pedro Ctra. de Miraflores  (km 34) 28770 Colmenar Viejo Madrid
46890 DEPARTAMENTO DE ENERGIA Avenida Computense 40 28071 Madrid (Madrid) 
46893 DEPARTAMENTO DE INVESTIGACION BASICA  Avenida Computense 40 28071 Madrid (Madrid) 
46892 DEPARTAMENTO DE TECNOLOGIA Avenida Computense 40 28071 Madrid (Madrid)
48863 LABORATORIO NACIONAL DE FUSION http://www.fusion.ciemat.es/inicio/visitenos/ Avenida Computense 40 28071 Madrid (Madrid)  Lat 40.45460, Long -3.72864
31793 BIBLIOTECA NACIONAL DE CIENCIAS DE LA SALUD tiene dos sedes (http://www.isciii.es/ISCIII/es/contenidos/fd-el-instituto/fd-organizacion/fd-estructura-directiva/fd-subdireccion-general-redes-centros-investigacion2/fd-centros-unidades2/fd-biblioteca-nacional-ciencias-salud/fd-sobre-la-biblioteca-ciencias-salud/quienes-somos-biblioteca-cs.shtml) 
La primera en C/ Sinesio Delgado, 4 (entrada por Avda. Monforte de Lemos, 5)  28029 - Madrid en el Campus de Chamartin del Instituto de la Salud Carlos III en los pabellones 7 y 8 
La segunda en Carretera de Majadahonda a Pozuelo km 2,2 28220 Majadahonda (MADRID) ESPAÑA Lat   40,459551, long  -3,864592
31803 ESCUELA NACIONAL DE SANIDAD ( http://www.isciii.es/ISCIII/es/contenidos/fd-el-instituto/fd-organizacion/fd-estructura-directiva/fd-subdireccion-general-investigacion-terapia-celular-medicina-regenerativa/fd-centros-unidades/fd-escuela-nacional-sanidad/contacto_esc-n-sanidad-1.shtml) C/ Monforte de Lemos 1, Pabellón 8. 28029  Madrid, España

**Comment by dfjhh** [comment]
36441 DIRECCION PROVINCIAL DE ALBACETE - INSS (https://www.informa.es/directorio-empresas/Empresa_INSS-ALBACETE-DIRECCION-PROVINCIAL.html) Avenida de España 31, Albacete 
36462 DIRECCION PROVINCIAL DE CEUTA - INSS (https://www.paginasamarillas.es/a/inss/ceuta/) Calle Alcalde Manuel Olivencia Amor s/n 51001 Ceuta
36416 DIRECCION PROVINCIAL DE ILLES BALEARS - INSS (https://www.paginasamarillas.es/search/inss/all-ma/illes-balears/all-is/all-ci/all-ba/all-pu/all-nc/1?what=Inss&where=Baleares&ub=false&qc=true) Calle Dezcallar i Net 3, 7003 Palma (Islas Baleares)
36436 DIRECCION PROVINCIAL DE LAS PALMAS ( https://www.paginasamarillas.es/search/inss/all-ma/all-pr/all-is/palmas/all-ba/all-pu/all-nc/1?what=Inss&where=Palmas&ub=false&pc=Pontevedra%26las+Palmas&qc=true) Calle León y Castillo 322, 35007 Las Palmas de Gran Canaria
30463 DISTRITO MARITIMO DE EL PUERTO DE SANTA MARIA ( https://www.fomento.gob.es/el-ministerio/contacte-con-fomento/marina-mercante/distritos/distritosmaritimos ) Muelle Exterior, s/n 11500 Puerto Santa María Cádiz

**Comment by s-nt-s** [comment]
Gracias ¿pero puedes escribirlo en el formato de `cod_dir_latlon.txt`?
```
<codigo>      <latlon>      <dirección postal>
```

**Comment by dfjhh** [comment]
Hay lo tienes, 31793, la he repetido con las dos sedes que tiene.

48836 41.7035721,-4.6634777 Base Militar El Empecinado Carretera de Cabezon, s/n, 47155 Santovenia de Pisuerga (Valladolid)
28959 36.52296,-6.28436 Plaza de San Severiano, 3, 11007 Cadiz (Cadiz)
28197 40.62867429,-3.88286022 Carretera de Torrelodones a Colmenar Viejo, km 10,7,  28240 Hoyo de Manzanares (Madrid)
28276 40.6802742,-3.78421701 Base Logística de San Pedro Ctra. de Miraflores,km 34, 28770 Colmenar Viejo (Madrid)
46890 40.45444326,-3.7283969 Avenida Computense, 40, 28071 Madrid (Madrid)
46893 40.45444326,-3.7283969 Avenida Computense, 40, 28071 Madrid (Mad
46892 40.45444326,-3.7283969 Avenida Computense, 40, 28071 Madrid (Madrid)
48863 40.45460,3.72864 Avenida Computense, 40, 28071 Madrid (Madrid)
31793 40.4753922,-3.6900447 Avda. Monforte de Lemos, 5, 28029 Madrid (Madrid)
31793 40,459551,-3,864592 Carretera de Majadahonda a Pozuelo, km 2,2, 28220 Majadahonda (Madrid)
31803 40.4753922,-3.6900447 Avda. Monforte de Lemos, 5, 28029 Madrid (Madrid)
36441 38.9855929,-1.85419654 Avda. de España, 31, 02002 Albacete (Albacete)
36462 35.8872292,-5.3049103 Calle Alcalde Manuel Olivencia Amor, s/n, 51001 Ceuta (Ceuta)
36416 39.5770186,2.6491093 Calle Dezcallar i Net, 3, 7003 Palma (Islas Baleares)
36436 28.13814,-15.42994  Calle León y Castillo, 322, 35007 Las Palmas de Gran Canaria (Las Palmas)
30463 36.5911131,-6.2266604 Muelle Exterior, s/n, 11500 Puerto Santa María (Cádiz)

**Comment by dfjhh** [comment]
Unos pocos más. La última tiene 2 sedes.

28213 41.5928836,-4.7601888 Carretera de Rueda, km 0,5, 47153 Valladolid (Valladolid)
49754  41.6477913,-0.8851905 Plaza de Aragón, 9, 50004 Zaragoza (Zaragoza)
28398 41.6695088,-1.0200418 Base Aérea de Zaragoza Carretera del Aeropuerto, s/n, 50071 Zaragoza (Zaragoza)
28289 39.4738481,-0.3694289 Plaza de Tetuán, 22, 46003 Valencia (Valencia)
28289  39.6194816, -0.4725756 Base Militar Jaime I Ctra. Portacoeli, s/n, 46117 Bétera (Valencia)

**Comment by s-nt-s** [comment]
Muy bien, ya solo queda averiguar donde esta `Centro de Comunicaciones de Cartagena (E02872502)`

**Comment by alosdie** [comment]
El Centro de Comunicaciones de Cartagena (E02872502) no aparece en el excel para actualizarlo. De todas formas aunque no encontré la dirección exacta "parece" que el Arsenal de la Armada de Cartagena, los Servicios generales de la Armada y otros organismo están juntos en la zona del puerto deportivo de Cartagena => 37.6004085,-0.9886661

**Comment by s-nt-s** [comment]
Bueno, pues por ahora lo degaremos así.
