### ISSUE TITLE
Puesto marcado como no vacante

### ISSUE THREAD

**Issue by victorgaldamez** [s-nt-s/TAI-Madrid#26]
Buenas,

Comentar que el puesto siguiente:

Organismo MINISTERIO DE TRABAJO, MIGRACIONES Y SEGURIDAD SOCIAL
Centro directivo S. DE E. DE LA SEGURIDAD SOCIAL
Unidad UNIDAD PROVINCIAL DE INFORMATICA DE HUELVA
Puesto ADMINISTRADOR / ADMINISTRADORA DEL SARTIDO
Nivel 21
Estado Vacante
Grupo A2C1
Complemento específico 4955,58 €
Código 4673068

Sigue vacante en Huelva pero sin embargo se marca como no vacante en el mapa, por si se puede corregir de alguna forma.

Desde la TGSS de Huelva me indican que ese puesto vacante pertenece al GISS.

Espero sirva de ayuda, un saludo.

**Comment by victorgaldamez** [comment]
También he visto este puesto vacante en Huelva, como operador de consola, que no aparece en el mapa:

Organismo MINISTERIO DE ECONOMIA Y EMPRESA
Centro directivo INSTITUTO NACIONAL DE ESTADISTICA (INE), O.A.
Unidad DELEGACION PROVINCIAL DEL INE DE HUELVA
Puesto OPERADOR / OPERADORA DE CONSOLA
Nivel 16
Estado Vacante
Grupo C1C2
Complemento específico 4056,36 €
Código 3335780

**Comment by s-nt-s** [comment]
Hola

Eso era debido a que los `RPT` han cambiado pero el mapa no se habia vuelto a generar.
El motivo por el que no se habia vuelto a generar es porque no confio en que los nuevos `RPT` esten bien, ya que desaparecen un gran número de puestos que sabemos que aún existe.

Se habla del tema en https://github.com/s-nt-s/TAI-Madrid#modificaci%C3%B3n-para-la-v2
