### ISSUE TITLE
colaborar 

### ISSUE THREAD

**Issue by franpola** [s-nt-s/TAI-Madrid#31]
hola, no soy programador pero acabo de aprobar en esta ultima convocatoria. si se puede colaborar de alguna forma para actualizar o hacer cualquier cosa que sirva a los compañeros estaria dispuesto.

un saludo

**Comment by s-nt-s** [comment]
Hola

Lo mejor es que hagas un fork del proyecto y reclutes gente entre los aprobados de tu convocatoria.
Yo ya no le doy soporte a este proyecto.
