### ISSUE TITLE
Puesto descartado: TECNICO / TECNICA DE TELECOMUNICACIONES

### ISSUE THREAD

**Issue by alosdie** [s-nt-s/TAI-Madrid#4]
Pendiente comprobar el resto de los datos en RPT para este tipo de puestos por si pudieran ser en algunos casos destinos TAI.

**Comment by s-nt-s** [comment]
¿seguro que ese puesto puede ser TAI? no lo tengo claro.

**Comment by alosdie** [comment]
Posiblemente no, seguro que es de defensa o adif, pero lo puse más que nada para recordar revisarlo, no incluirlo.

**Comment by s-nt-s** [comment]
los puestos de defensa y adif hay que descartarlos? por que?
