### ISSUE TITLE
Puesto descartado: ADMINISTRADOR / ADMINISTRADORA DE RED

### ISSUE THREAD

**Issue by gondev** [s-nt-s/TAI-Madrid#6]
A falta de confirmarlo buscando en la RPT correspondiente, aparece este puesto en los descartados dentro de resto_puestos.txt

**Comment by gondev** [comment]
Por no duplicar el issue, otro más: TECNICO / TECNICA DE GESTION DE RED

**Comment by s-nt-s** [comment]
hecho
