### ISSUE TITLE
Puestos descartados que sí podrían ofrecerse a TAI

### ISSUE THREAD

**Issue by ricardoarroyo** [s-nt-s/TAI-Madrid#7]
ADMINISTRADOR / ADMINISTRADORA DE RECURSOS INFORMATICOS Y COMUNICACIONES
Según: https://www.taiestado.com/comunidad/viewtopic.php?t=139

OPERADOR / OPERADORA DE CONSOLA
OPERADOR / OPERADORA PERIFERICO
OPERADOR / OPERADORA PERIFERICO N15
Según: https://www.buscaoposiciones.com/foro/Oposiciones-Junta-de-Andalucia-fmen-1038637-5025230.htm (parece que también se ofrecen a Administrativos)

**Comment by victorgaldamez** [comment]
Existe un puesto en concreto, ADMINISTRADOR DEL SARTIDO, que pienso se ha omitido.

Aunque el nivel suele ser de los más altos y puede no se ofrezcan a nuevo ingreso si sé que son puestos ocupados por TAIs.

**Comment by s-nt-s** [comment]
¿Puedes darme un idPuesto de ejemplo de `ADMINISTRADOR DEL SARTIDO`? No encuentro ninguno.

**Comment by victorgaldamez** [comment]
Organismo MINISTERIO DE EMPLEO Y SEGURIDAD SOCIAL
Centro directivo S. DE E. DE LA SEGURIDAD SOCIAL
Unidad UNIDAD PROVINCIAL DE INFORMATICA DE HUELVA
Puesto ADMINISTRADOR / ADMINISTRADORA DEL SARTIDO
Nivel 21
Estado Vacante
Grupo A2C1
Complemento específico 4876,20 €
Código 4673068

¿Vale con esa información?

**Comment by s-nt-s** [comment]
Si, muchas gracias.

**Comment by s-nt-s** [comment]
Puestos añadidos
