### ISSUE TITLE
Lan Lon en excel

### ISSUE THREAD

**Issue by javierbds** [s-nt-s/TAI-Madrid#8]
Aun no se usa la excel pero veo que algunas chinchetas no estan donde debieran y tampoco tengo claro donde poner la lat lon correcta en la excel (y además ya no puedo editar).
http://www.mapcoordinates.net/en para obtener latlon

**Ejemplo Jardin Botanico**
JB (20, Madriz), [30.08.18 11:59]
He intentado ver de donde se saca la lat lon de los puestos en la excel ... Algunas lat lon estan desplazadas unos cientos de metros Por ejemplo el jardin botanico es 40.4122193, -3.6919986 pero en el mapa aperece en la parte superior izquierda del Retiro 😇

S (75, Madrid), [30.08.18 12:05]
Aun no cruzo con el excell, por ahora los unicos latlon que usa el mapa son los que se obtienen de la web del csic y de la web de administracion.gob.es

JB (20, Madriz), [30.08.18 12:13]
quería decir derecha 😜

JB (20, Madriz), [30.08.18 12:23]
Y el Jardin Botanico aparece en unidades (que no tienen lat lon)  pero no en direcciones? 27646 que es su id de unidad   En puestos aparece como 40.4121601,-3.6919537 (y no lo puedo editar) Me gustan las plantas 🍉

JB (20, Madriz), [30.08.18 12:23]
idPuesto 4678471

**Comment by s-nt-s** [comment]
Pasa solo en algunos puntos ¿o todos estan desplazados en la misma medida?

**Comment by javierbds** [comment]
Solo en algunos puntos.
De hecho, en algunos casos es al reves (Google coloca mal la Plaza de Jacinto Benavente (300m demasiado a la derecha) y la solución actual coloca la chincheta no ya en la plaza si no en los edificios correctos.

**Comment by javierbds** [comment]
Otro caso, el CEDEX  (algunos organismos proporcionan sus datos mal en la propia administración):

Nosotros lo sacamos (del la misma fuente?) que 
https://administracion.gob.es/pagFront/espanaAdmon/directorioOrganigramas/fichaUnidadOrganica.htm?idUnidOrganica=776#.W4j5lugzZQJ


El link bueno es https://www.google.com/maps/search/?api=1&query=40.4095249,-3.6884805

Creo. Y requiere abrir el detalle de oficinas de la pagina que nosotros usamos
https://administracion.gob.es/pagFront/espanaAdmon/directorioOrganigramas/listarOficinas.htm?idUnidOrganica=776&origenUO=&volver=volverFicha&cIdUdOrganica=E00125801#.W4j5yOgzZQI

**Comment by s-nt-s** [comment]
En http://www.cedex.es/CEDEX/LANG_CASTELLANO/ORGANISMO/PRESENTACION/DIRECTORIO/ tambien pone Alfonso XII, y de hecho no sale Juan Varela. ¿Desde cuando esta el CEDEX en Juan Varela?

**Comment by s-nt-s** [comment]
He escrito un (README.me)[https://github.com/s-nt-s/TAI-Madrid/tree/master/mapa] para explicar como esta hecho el mapa y como podeis hacer `pull requests` que corrijan las direcciones que estan mal o añadan las que faltan.

**Comment by javierbds** [comment]
![image](https://user-images.githubusercontent.com/9029066/45164876-caa85980-b1f3-11e8-8ed9-a358d9a8d240.png)

Tecnicamente es Alfoso XII **3-5**, pero si quiere localizarlo debes ir a la calle Juan Varela (mirando el mapa no he ido, pero la chincheta aparecia en medio de la calle Alfonso XII (como ALfonso XII S/N).

**Comment by javierbds** [comment]
![image](https://user-images.githubusercontent.com/9029066/45165792-d4cb5780-b1f5-11e8-90af-795f1353f7f5.png)
En la esquina superior izquierda esta la chincheta del mapa en el borde inferior esta el edificio al que corresponde (solo se ve una parte, el trocito marron debajo del labo del CEDEX).

**Comment by s-nt-s** [comment]
Cambio las coordenadas de 49031 y 27646 siguiendo tus indicaciones. Gracias
