### ISSUE TITLE
Posibles puestos omitidos

### ISSUE THREAD

**Issue by gillemus** [s-nt-s/TAI-Madrid#9]
En la [convocatoria de 2016](http://www.boe.es/boe/dias/2018/01/26/pdfs/BOE-A-2018-991.pdf), sale una plaza de GESTOR/A DE INFORMÁTICA en el PRAT DEL LLOBREGAT. Referencia 4749769 Nivel 16.
Y en Huesca, en la Relación de Puestos de Trabajo, aparece ligado a la [Secretaría de Estado de la Seguridad social](http://transparencia.gob.es/transparencia/transparencia_Home/index/PublicidadActiva/OrganizacionYEmpleo/Relaciones-Puestos-Trabajo/RPT-MTMS.html) un puesto de OPERADOR/A ESPECIALISTA, nivel 16, referencia código 2170368.
Espero haber servido de ayuda

**Comment by s-nt-s** [comment]
El 4749769 ya esta apareciendo en https://s-nt-s.github.io/TAI-Madrid/724/08/index.html

Y aunque efectivamente el 2170368 no aparece, ¿por qué crees que es un puesto TAI?

**Comment by pikachuEMR** [comment]
Hay puestos de OPERADOR ESPECIALISTA ofertados y asignados a TAIs en la convocatoria del año 2008: https://www.boe.es/boe/dias/2008/12/16/pdfs/A50441-50448.pdf

También se ofertaron en un concurso reciente para la Gerencia de Informática de la Seguridad Social (GISS): https://www.boe.es/boe/dias/2016/04/30/pdfs/BOE-A-2016-4149.pdf. En la descripción de funciones se puede observar que sus funciones son análogas a las de ANALISTA PROGRAMADOR o TECNICO/A AUXILIAR DE INFORMATICA. De los 5 puestos de OPERADOR/A ESPECIALISTA ofertados, 4 quedaron desiertos, y 1 fue ocupado por una funcionaria del Cuerpo Administrativo de la Administración de la Seguridad Social [cód. A1616]: https://www.boe.es/boe/dias/2016/11/01/pdfs/BOE-A-2016-10033.pdf

**Comment by s-nt-s** [comment]
Ok, añado `OPERADOR/A ESPECIALISTA` al filtro.
